# Generated by Django 4.0.2 on 2022-03-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('roll', models.IntegerField()),
                ('city', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
